In [3]:
import numpy as np


In [4]:
a=np.ones((4,4))
b=np.random.randint(6,size=(2,2))
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 3]
 [2 3]]


In [5]:
b=b.reshape(4,4)

ValueError: cannot reshape array of size 4 into shape (4,4)

In [ ]:
def convolution(img,filt,stride):
    shape_0 = (img.shape[0]-filt.shape[0])//stride + 1
    shape_1 = (img.shape[1]-filt.shape[1])//stride + 1
    
    cnn = np.zeros((shape_0,shape_1))
    
    for i in range(shape_0):
        for j in range(shape_1):
            h = stride*i
            h_end = h+ filt.shape[0]
            w=j*stride
            w_end = w+filt.shape[1]
            
            #cnn[i,j] = np.sum(np.multiply(img[h:h_end,w:w_end],filt))
            print(img[h:h_end,w:w_end],img[h:h_end,w:w_end]==filt[i,j])
            
            
          
            
    #return cnn 

In [ ]:
convolution(a,b,2)

In [ ]:
a=np.random.randint(100,size=(4,4))
print(a)

In [ ]:
b=np.array(([90,48],[91,45]))

In [ ]:
a=np.random.randint(9,size=(4,3,5,3))
print(a.shape)
a=a.reshape(4,-1)
print(a.shape)

In [ ]:
print(a==b)

In [66]:
f =  np.array(([1,1,1],[0,0,0],[1,1,1])).T
print(f)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [67]:
img = np.array(([1  ,2,  3,  4,  5 ] ,    
    [6  ,7  ,8  ,9 , 10],         
    [11 ,12, 13, 14, 15],          
    [16 ,17 ,18 ,19 ,20],
    [21 ,22, 23, 24, 25]))
print(img)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [230]:

def full_conv(img,siz,f):
    r=[]
    
    z=0
    size = siz
    for i in range(1,img.shape[0]+size,1):
        k=0

        if i>size:
                z=i-size


        for j in range(1,img.shape[1]+size,1):

            if j>size:
                k=j-size

            print(img[z:i,k:j],f[z:i,k:j])
            #print(i,z,k,j,end="   ")
        
    #return r
def cnv(img,size,f):
    
    a_3=0
    
    maxx = size
    k=maxx
    
    for j in range(1,img.shape[0]+maxx):
        a_1=0
        m = maxx
        a_4=j
        if  j>= maxx + 1:
            a_3 +=1
        if a_4 > img.shape[0]:
            a_4 = img.shape[0]
            k-=1
        
        
    
        for i in range(1,img.shape[1]+maxx):

            a_2=i

            if i >= maxx + 1:
                a_1 +=1
            if a_2 > img.shape[1]:
                a_2 = img.shape[1]
                m-=1
            #print(a_2-i+a_1)#,a_2,a_1,i-a_1,i-a_2,i)   a[m-(a_2-a_1):m],
            #print(img[a_3:a_4,a_1:a_2])
            #print(np.sum(np.multiply(img[a_3:a_4,a_1:a_2],f[k-(a_4-a_3):k,m-(a_2-a_1):m])),end="     ")
            print(img[a_3:a_4,a_1:a_2],f[k-(a_4-a_3):k,m-(a_2-a_1):m],end = "   ")
        print()
        print()
        print()



In [262]:
def conv(imag,filt,stride,pad):

    cnv_1 = (imag.shape[0] + 2*pad - filt.shape[0])//stride + 1
    cnv_2 = (imag.shape[1] + 2*pad - filt.shape[1])//stride + 1
    
    b = np.zeros((filt.shape[0]*filt.shape[1],cnv_1*cnv_2),dtype="float64")
    
    z=0
    
    for i in range(cnv_1):
        v_start = i * stride
        v_end = v_start + filt.shape[0]
        for j in range(cnv_2):

            
            h_start = j * stride
            h_end = h_start + filt.shape[1]
            
            b[:,z] = imag[v_start:v_end,h_start:h_end].flatten()
            #print(imag[v_start:v_end,h_start:h_end],end=" ")
            z+=1
       
    b=np.dot(np.reshape(filt,(filt.shape[0]*filt.shape[1],1)).T,b)
    
    return np.reshape(b,(cnv_1,cnv_2)) 


In [165]:
cnv(a,2,f)


4     11     18     9     


18     37     47     21     


36     67     77     33     


14     23     26     9     




In [ ]:
for i in range(7):
    print(a[i])
    

In [73]:
print(conv(np.pad(img,(2,2),"constant"),f,1,0),conv(np.pad(img,(2,2),"constant"),f,2,0))

[[  1.   2.   4.   6.   8.   4.   5.]
 [  7.   9.  18.  22.  26.  13.  15.]
 [ 18.  21.  42.  48.  54.  27.  30.]
 [ 33.  36.  72.  78.  84.  42.  45.]
 [ 48.  51. 102. 108. 114.  57.  60.]
 [ 37.  39.  78.  82.  86.  43.  45.]
 [ 21.  22.  44.  46.  48.  24.  25.]] [[  1.   4.   8.   5.]
 [ 18.  42.  54.  30.]
 [ 48. 102. 114.  60.]
 [ 21.  44.  48.  25.]]


In [ ]:
a=[9,4,7,1]
b=[1,2,3,4,5]
print(a,"\n",b)

In [ ]:
a_1=0
maxx = 4
m = maxx
for j in range(1,len())
    for i in range(1,len(b)+maxx):

        a_2=i

        if i >= maxx + 1:
            a_1 +=1
        if a_2 > len(b):
            a_2 = len(b)
            m-=1
        #print(a_2-i+a_1)#,a_2,a_1,i-a_1,i-a_2,i)
        print(a[m-(a_2-a_1):m],b[a_1:a_2])
     

In [ ]:
k=1
for i,j in zip(range(7),range(2)):
    print(i,j)
    

In [ ]:
i=-1
j=-1
a=[1,2,3]
while i <7 and j<3:
    
    
    i+=1
    j+=1
    
    if j==3:
        j=0
    print(i,j,i-j)
    

In [231]:
a=np.array((['Z11','Z12'],['Z21','Z22']),dtype=object)
b=np.array((['W22','W21'],['W12','W11']),dtype=object)
print(a,b)

[['Z11' 'Z12']
 ['Z21' 'Z22']] [['W22' 'W21']
 ['W12' 'W11']]


In [232]:
cnv(a,2,b)

[['Z11']] [['W11']]   [['Z11' 'Z12']] [['W12' 'W11']]   [['Z12']] [['W12']]   


[['Z11']
 ['Z21']] [['W21']
 ['W11']]   [['Z11' 'Z12']
 ['Z21' 'Z22']] [['W22' 'W21']
 ['W12' 'W11']]   [['Z12']
 ['Z22']] [['W22']
 ['W12']]   


[['Z21']] [['W21']]   [['Z21' 'Z22']] [['W22' 'W21']]   [['Z22']] [['W22']]   




In [76]:
a=np.array(([1,2,3,1],[2,4,5,6],[3,7,8,9],[2,1,2,1]))
fl=np.array(([1,3],[2,4]))
print(a,fl)

[[1 2 3 1]
 [2 4 5 6]
 [3 7 8 9]
 [2 1 2 1]] [[1 3]
 [2 4]]


In [36]:
cnnv(a,3,f)

[[1]] [[4]]   [[1 2]] [[3 4]]   [[1 2 4]] [[1 3 4]]   [[2 4 5]] [[1 3 4]]   [[4 5]] [[1 3]]   [[5]] [[1]]   


In [41]:
print(np.pad(a,(1,1),"constant"))

[[0 0 0 0]
 [0 1 2 0]
 [0 4 5 0]
 [0 0 0 0]]


In [77]:
print(conv(a,fl,1,0))

[[27. 39. 40.]
 [48. 65. 75.]
 [32. 41. 43.]]


In [80]:
print(conv(a,fl,2,0))

[[27. 40.]
 [32. 43.]]


In [158]:
print(conv(np.pad(f,(2,2),"constant"),a,1,0))
print(conv(np.pad(a,(2,2),"constant"),f,1,0))

[[ 9. 26. 23. 14.]
 [33. 77. 67. 36.]
 [21. 47. 37. 18.]
 [ 9. 18. 11.  4.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  4. 11. 18.  9.  0.]
 [ 0. 18. 37. 47. 21.  0.]
 [ 0. 36. 67. 77. 33.  0.]
 [ 0. 14. 23. 26.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [270]:
a=np.random.rand(5,5)
f=np.random.rand(2,2)
print(f)

[[0.1005273  0.64421501]
 [0.39142387 0.01806386]]


In [271]:
print(conv(np.pad(f,(4,4),"constant"),np.rot90(a,2),1,0)==conv(np.pad(a,(1,1),"constant"),np.rot90(f,2),1,0))

[[ True  True  True  True  True  True]
 [ True  True False  True  True  True]
 [ True False  True  True False  True]
 [ True  True  True  True  True  True]
 [ True False  True False  True False]
 [ True  True  True  True  True  True]]


In [213]:
cnv(a,4,f)


2     6     12     20     28     36     44     52     60     48     34     18     


22     48     78     112     128     144     160     176     192     150     104     54     


60     126     198     276     300     324     348     372     396     306     210     108     


116     240     372     512     544     576     608     640     672     516     352     180     


188     384     588     800     832     864     896     928     960     732     496     252     


260     528     804     1088     1120     1152     1184     1216     1248     948     640     324     


332     672     1020     1376     1408     1440     1472     1504     1536     1164     784     396     


404     816     1236     1664     1696     1728     1760     1792     1824     1380     928     468     


476     960     1452     1952     1984     2016     2048     2080     2112     1596     1072     540     


384     774     1170     1572     1596     1620     1644     1668     1692     1278     858     4