In [1]:
from time import *
import numpy as np



In [18]:
a = np.random.rand(30,30)
b = np.random.rand(30,30)

print(b.shape)

(30, 30)


In [91]:
a = np.random.rand(3,3)



In [92]:
print(a.shape)
    

(3, 3)


In [96]:
def padd(a,size):
    
    b=np.zeros((a.shape[0]+size*2,a.shape[1]+size*2))
    
    print(b.shape)
    

In [103]:
print(np.pad(a,((4,4),(4,4)),"constant").shape)
padd(a,40)

(11, 11)
(83, 83)


In [58]:
print(a)

[[0.41879648 0.19453014 0.67911079]
 [0.15911658 0.32255218 0.10038692]
 [0.64476149 0.6272786  0.7710815 ]]


In [140]:
ar = np.random.rand(6,6)
print(ar)

[[0.98577754 0.81481626 0.63984738 0.50822312 0.24310757 0.26261313]
 [0.70279644 0.67864466 0.68245168 0.47009677 0.22058851 0.74714476]
 [0.44253944 0.74654088 0.87577529 0.97637745 0.11512438 0.91640958]
 [0.3316812  0.46971016 0.39682985 0.06487198 0.58328058 0.48093036]
 [0.86706679 0.02427078 0.75430586 0.78677436 0.5212923  0.66203046]
 [0.12013376 0.09668847 0.97968478 0.45087081 0.16340552 0.07565786]]


In [141]:
print(ar[1,0:2,0:3])

IndexError: too many indices for array

In [171]:
def parse(a,stride,filterr,pad):
    
    n_0,n_1 =  a.shape
    f_0,f_1 = filterr.shape
    
    shape_0 = (n_0 + 2*pad -f_0)//stride + 1
    shape_1 = (n_1 + 2*pad -f_1)//stride + 1

    conv = np.zeros((shape_0,shape_1))
    c=0
    b=0
    
    for i in range((n_0+2*pad -f_0)//stride + 1):
        
        c=0

        for j in range((n_1+2*pad -f_1)//stride + 1):
           #print(a[b:b+f_0,c:c+f_0])
            print(b,c)
            conv[i,j]=sum(sum(np.multiply((a[b:b+f_0,c:c+f_0]),filterr)))
            c=c+stride
           

        b=b+stride
        
    return conv
    
    
    

In [172]:
ar=np.array(([2,3,7,4,6,2,9],[6,6,9,8,7,4,3],[3,4,8,3,8,9,7],[7,8,3,6,6,3,4],[4,2,1,8,3,4,6],[3,2,4,1,9,8,3],[0,1,3,9,2,1,4]))
f=np.array(([3,4,4],[1,0,2],[-1,0,3]))
parse(ar,2,f,0)

0 0
0 2
0 4
2 0
2 2
2 4
4 0
4 2
4 4


array([[ 91., 100.,  88.],
       [ 69.,  91., 117.],
       [ 44.,  72.,  74.]])

In [21]:
m,n = ar.shape
print(m,n)

3 3


In [131]:
a=np.ones((1,3,1
          ))

In [132]:
print(a)

[[[1.]
  [1.]
  [1.]]]


In [139]:
W = np.random.randn(3,3,2,5)
print(W)

[[[[ 1.99365963  0.29507539  0.85632581 -0.06321149  1.75937462]
   [-1.3867443   1.10391631  1.03549754 -0.75985455  0.52193345]]

  [[ 0.46063881 -1.27035362  0.1355303   0.25259128  0.53169579]
   [ 1.6978036  -0.33653596 -1.32863849  0.7049711  -0.08987692]]

  [[ 1.8339178  -0.60414814 -0.229422    0.77994201  0.05378389]
   [-1.69767173  1.79547015  1.04656109 -1.18727333 -0.15200278]]]


 [[[ 1.26956031  0.45509388  0.74021635  1.25227884  0.45251021]
   [-0.18270384  1.01210285 -0.47227854 -1.72591905 -0.34390673]]

  [[-0.47622136  0.28242245  0.69515539 -0.55281825 -1.20134227]
   [ 0.39954737 -1.64359714 -1.12209639 -1.85993119  0.71543662]]

  [[-0.23968675 -0.71708742  0.20198155 -0.98305441  0.31445695]
   [-0.83080755 -0.14123383 -0.29829219 -0.05703639  0.63647937]]]


 [[[ 1.57885412 -0.74297509  2.32968319 -0.08447706 -1.29800727]
   [-0.33119307 -1.85392592 -0.95453038 -0.14574764 -0.44514966]]

  [[ 0.40886842 -0.54890348 -1.52718239 -0.16295033 -0.16290345]
   [-0.

In [154]:
c=np.random.rand(3,3)
d=np.random.rand(3,3)
print(c,d)

[[0.92401001 0.15116891 0.43868769]
 [0.65018485 0.74266894 0.29676453]
 [0.62819876 0.02171588 0.58648592]] [[0.18737623 0.52668272 0.08925214]
 [0.13829966 0.76186181 0.84193524]
 [0.14845636 0.54071295 0.69346618]]


In [156]:
sum(np.multiply(c,d))

array([0.35631796, 0.65717121, 0.69571848])

In [223]:
a=np.random.rand(2,3,6,6)
print(a)

[[[[0.14365324 0.22642567 0.38605449 0.66932703 0.13008967 0.0351197 ]
   [0.7784441  0.15412401 0.84656957 0.69097522 0.72550876 0.77834094]
   [0.82407551 0.62345069 0.73844736 0.85540707 0.63735785 0.36204444]
   [0.40203367 0.26883778 0.69095441 0.00677652 0.97774552 0.75153576]
   [0.28636983 0.44304916 0.30383446 0.42530771 0.69823357 0.03036626]
   [0.94772619 0.48085669 0.25150981 0.47674735 0.83762551 0.82055224]]

  [[0.12963023 0.41846591 0.28243139 0.98296181 0.04401671 0.45007897]
   [0.4794483  0.3767764  0.06604824 0.93908191 0.1773713  0.6755979 ]
   [0.72096643 0.67387764 0.06878544 0.6858516  0.2852219  0.7685716 ]
   [0.49381895 0.38234389 0.75705876 0.48753449 0.02244999 0.07340639]
   [0.39961685 0.28410876 0.1265946  0.98188887 0.62069354 0.9249673 ]
   [0.0593295  0.55287776 0.36282714 0.73591685 0.28048024 0.34485104]]

  [[0.60680199 0.92845001 0.69613289 0.7997861  0.27586296 0.56946992]
   [0.15759314 0.161837   0.08021913 0.68472524 0.95372713 0.33377808]
  

In [225]:
b=a[0,:,:,:]

In [226]:
print(b[0,0:3,0:3])

[[0.14365324 0.22642567 0.38605449]
 [0.7784441  0.15412401 0.84656957]
 [0.82407551 0.62345069 0.73844736]]


In [228]:
def pars(a,stride,filterr,pad):
    
    m,n,n_0,n_1 =  a.shape
    f_0 = filterr
    
    shape_0 = (n_0 + 2*pad -f_0)//stride + 1
    shape_1 = (n_1 + 2*pad -f_0)//stride + 1

    conv = np.zeros((shape_0,shape_1))
    c=0
    b=0
    
    for k in range(m):
        
        for u in range(n):
            b=0
            for i in range((n_0+2*pad -f_0)//stride + 1):

                c=0

                for j in range((n_1+2*pad -f_0)//stride + 1):
                    print(a[k,u,b:b+f_0,c:c+f_0])
                    print(k,u,b,c)

                    c=c+stride


                b=b+stride
        
    

In [229]:
pars(a,2,3,0)

[[0.14365324 0.22642567 0.38605449]
 [0.7784441  0.15412401 0.84656957]
 [0.82407551 0.62345069 0.73844736]]
0 0 0 0
[[0.38605449 0.66932703 0.13008967]
 [0.84656957 0.69097522 0.72550876]
 [0.73844736 0.85540707 0.63735785]]
0 0 0 2
[[0.82407551 0.62345069 0.73844736]
 [0.40203367 0.26883778 0.69095441]
 [0.28636983 0.44304916 0.30383446]]
0 0 2 0
[[0.73844736 0.85540707 0.63735785]
 [0.69095441 0.00677652 0.97774552]
 [0.30383446 0.42530771 0.69823357]]
0 0 2 2
[[0.12963023 0.41846591 0.28243139]
 [0.4794483  0.3767764  0.06604824]
 [0.72096643 0.67387764 0.06878544]]
0 1 0 0
[[0.28243139 0.98296181 0.04401671]
 [0.06604824 0.93908191 0.1773713 ]
 [0.06878544 0.6858516  0.2852219 ]]
0 1 0 2
[[0.72096643 0.67387764 0.06878544]
 [0.49381895 0.38234389 0.75705876]
 [0.39961685 0.28410876 0.1265946 ]]
0 1 2 0
[[0.06878544 0.6858516  0.2852219 ]
 [0.75705876 0.48753449 0.02244999]
 [0.1265946  0.98188887 0.62069354]]
0 1 2 2
[[0.60680199 0.92845001 0.69613289]
 [0.15759314 0.161837   0.08

In [227]:
print(a[0,0,0:3,0:3])

[[0.14365324 0.22642567 0.38605449]
 [0.7784441  0.15412401 0.84656957]
 [0.82407551 0.62345069 0.73844736]]


In [283]:
def par(a,stride,filterr,pad):
    
    n,n_0,n_1 =  a.shape
    f_0 = filterr
    
    shape_0 = (n + 2*pad -f_0)//stride + 1
    shape_1 = (n_0 + 2*pad -f_0)//stride + 1
    
    print(shape_0,shape_1)

    conv = np.zeros((shape_0,shape_1))
    c=0
    b=0
    y=0

    for u in range((n+2*pad -f_0)//stride + 1):
        
        b=0
        for i in range((n_0+2*pad -f_0)//stride + 1):

            c=0

            for j in range(n_1):
               
                
                #print(a[y:y+f_0,b:b+f_0,])
                print(y,y+f_0,b,b+f_0)
                print(u*stride,u*stride+f_0,i*stride,i*stride+f_0)
                print()
                    
                
                c=c+stride
                
                


            b=b+stride
            
        y=y+stride

In [284]:
b=np.random.rand(4,4,6)
par(b,1,3,0)
                 

2 2
0 3 0 3
0 3 0 3

0 3 0 3
0 3 0 3

0 3 0 3
0 3 0 3

0 3 0 3
0 3 0 3

0 3 0 3
0 3 0 3

0 3 0 3
0 3 0 3

0 3 1 4
0 3 1 4

0 3 1 4
0 3 1 4

0 3 1 4
0 3 1 4

0 3 1 4
0 3 1 4

0 3 1 4
0 3 1 4

0 3 1 4
0 3 1 4

1 4 0 3
1 4 0 3

1 4 0 3
1 4 0 3

1 4 0 3
1 4 0 3

1 4 0 3
1 4 0 3

1 4 0 3
1 4 0 3

1 4 0 3
1 4 0 3

1 4 1 4
1 4 1 4

1 4 1 4
1 4 1 4

1 4 1 4
1 4 1 4

1 4 1 4
1 4 1 4

1 4 1 4
1 4 1 4

1 4 1 4
1 4 1 4



In [279]:
print(b)

[[[0.69626277 0.27912523 0.46285606 0.32544447 0.33357592 0.71283174]
  [0.19776782 0.17231293 0.78432598 0.06326541 0.91736701 0.59777689]
  [0.79543178 0.70468951 0.70962798 0.18230211 0.11815221 0.62572731]
  [0.73519578 0.31140425 0.7706609  0.31860786 0.77674351 0.79217211]]

 [[0.58652159 0.81855297 0.05700569 0.86778017 0.76392208 0.04796645]
  [0.76045488 0.29754619 0.08583394 0.59571802 0.31907002 0.23079286]
  [0.70839601 0.4792386  0.60390741 0.8880164  0.90348273 0.88674124]
  [0.40144708 0.92165013 0.38526861 0.55708893 0.70262088 0.8292222 ]]

 [[0.59355132 0.11062288 0.76171333 0.73480665 0.5990099  0.27883126]
  [0.22088823 0.23234395 0.06966165 0.64784502 0.09946967 0.60413549]
  [0.91613701 0.57887867 0.9305501  0.67136349 0.80858213 0.64449798]
  [0.41923109 0.18970302 0.13649726 0.22274728 0.70847352 0.37253218]]

 [[0.55791208 0.06329464 0.18459773 0.76289865 0.00877381 0.38810081]
  [0.78611296 0.25999725 0.29450096 0.19871945 0.68739662 0.88445699]
  [0.78342436 

In [295]:
a=np.random.rand(2,3,3,3)
print(a)

[[[[0.28884157 0.02457164 0.98234425]
   [0.35897859 0.0641183  0.22657741]
   [0.33583969 0.26696539 0.70903859]]

  [[0.60456336 0.96460272 0.87532723]
   [0.41333106 0.38619374 0.36584464]
   [0.51353066 0.27939438 0.3755702 ]]

  [[0.6428377  0.57951458 0.66392495]
   [0.72384692 0.56252699 0.41386607]
   [0.26381838 0.35931433 0.80048888]]]


 [[[0.59978519 0.25322183 0.63868616]
   [0.27623248 0.4233492  0.85091962]
   [0.99272046 0.6923349  0.28868386]]

  [[0.46138971 0.93935854 0.11253391]
   [0.99936556 0.74806131 0.8245787 ]
   [0.33660181 0.00553316 0.44759071]]

  [[0.4000002  0.32917574 0.66894993]
   [0.43039585 0.6777488  0.88922324]
   [0.88322126 0.88971331 0.10360586]]]]


In [304]:
print(a[1,0:3,0:3,0])

[[0.59978519 0.27623248 0.99272046]
 [0.46138971 0.99936556 0.33660181]
 [0.4000002  0.43039585 0.88322126]]
