In [1]:
import numpy as np
a = np.array([[32,33,222],[1,22,4]])
#
print(a)
b=np.sum(a,axis=1,keepdims = True)

print(b.shape)
print(a/b)

[[ 32  33 222]
 [  1  22   4]]
(2, 1)
[[0.11149826 0.11498258 0.77351916]
 [0.03703704 0.81481481 0.14814815]]


In [62]:
a = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27],[28,29,30]))
a=a.T
print(a)
print(a[0:,3:6])

[[ 1  4  7 10 13 16 19 22 25 28]
 [ 2  5  8 11 14 17 20 23 26 29]
 [ 3  6  9 12 15 18 21 24 27 30]]
[[10 13 16]
 [11 14 17]
 [12 15 18]]


In [92]:
m = a.shape[1]
c = 9
n=0
for i in range(10//c):
    
    print(a[0:,(i*c):(i+1)*c])
    
   
print(a[0:,c*(10//c):m])
    
print(a.shape,(m-(c*(10//c)) ))

[[ 1  4  7 10 13 16 19 22 25]
 [ 2  5  8 11 14 17 20 23 26]
 [ 3  6  9 12 15 18 21 24 27]]
[[28]
 [29]
 [30]]
(3, 10) 1


In [94]:
print(np.sqrt(a))

[[1.         2.         2.64575131 3.16227766 3.60555128 4.
  4.35889894 4.69041576 5.         5.29150262]
 [1.41421356 2.23606798 2.82842712 3.31662479 3.74165739 4.12310563
  4.47213595 4.79583152 5.09901951 5.38516481]
 [1.73205081 2.44948974 3.         3.46410162 3.87298335 4.24264069
  4.58257569 4.89897949 5.19615242 5.47722558]]


In [4]:
import numpy as np
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(image)
print(image.shape)

[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]
(3, 3, 2)


In [36]:
a=np.array([1,0.7,0.5,0.4,0.5])
b = np.where(a>=0.5,0,1)
print(b)

[0 0 0 1 0]
